module WelcomeHelper
	@generic_words = ["the", "and", "to", "of", "a", "in", "for", "you", "is", "at", "be", "on", "with", "will", "this", "we", "your", "are", "that", "all", "by", "if", "it", "or", "as", "i", "from", "so", "our", "have", "pm", "new", "us", "get", "come", "not", "its", "can", "an", "my", "about", "but", "th", "me", "more", "there", "up", "just", "dont", "only", "year", "some", "please", "their", "was", "no", "like", "bring", "do", "how", "what", "one", "well", "invite", "see", "who", "out", "his", "has", "years", "her", "want", "know", "would", "tickets", "into", "may", "take", "they", "help", "other", "now", "them", "ticket", "each", "need", "facebook", "anyone", "go", "such", "after", "been", "any", "good", "last", "let", "center", "also", "best", "join", "including", "here", "first", "way", "back", "welcome", "l", "presents", "should", "find", "going", "invited", "open", "special", "lets", "grade", "includes", "off", "than", "through", "most", "end", "where", "next", "before", "top", "much", "when", "parti", "continuation", "im", "d", "gray", "week", "again", "oh", "were", "many", "place", "few", "say", "ever", "together", "something", "must", "thats", "then", "right", "level", "got", "fair", "because", "others", "down", "thanks", "youre", "s", "part", "guests", "he", "sure", "three", "gonna", "every", "am", "available", "taking", "without", "st", "over", "annual", "lobby", "which", "person", "n", "max", "featuring", "buy", "look", "rsvp", "really", "bryan", "miss", "starting", "had", "left", "long", "around", "page", "likes", "stop", "michael", "march", "show", "made", "big", "post", "put", "list", "getting", "eve", "feel", "didnt", "favorite", "area", "ask", "even", "real", "aug", "wear", "between", "wanna", "call", "along", "very", "able", "still", "these", "official", "host", "guys", "justin", "name", "she", "mum", "general", "check", "once", "youll", "keep", "largest", "own", "oct", "morgan", "great", "everything", "tomorrow", "events", "old", "october", "rd", "leave", "does", "cispa", "happy", "cant", "hope", "updated", "enough", "cover", "word", "itll", "another", "light", "better", "dear", "wait", "added", "coming", "feb", "nd", "cool", "yet", "too", "month", "door", "did", "worry", "fast", "never", "kathryn", "weve", "corazza", "probably", "minute", "thursday", "shit", "times", "later", "plan", "anybody", "days", "born", "round", "why", "paramount", "tell", "based", "looking", "early", "away", "second", "hey", "per", "little", "gb", "five", "across", "cut", "drive", "street", "already"]

	def randomized_background_gif
		images = ["3d_light_elves.gif", "ashton_kutcher.gif", "dobby_harry_potter_elf.gif", "elephant_kill_elf_LOR.gif", "elf_movie_elevator.gif", "elf_movie_escalator.gif", "elf_movie_street_crossing.gif", "elf_sculptors.gif", "facebook_logo.png", "nicholas_cage_elf.gif", "orlando_bloom_elf_LOR.gif", "worker_elves_factory_line.gif", "wow_dark_elf.gif"]
		images[rand(images.size)]
	end
end

